# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a9847a0e5493f5f1bad1a0e8d40f9c6d87adb9169c00947ca018f9b02349f9380e4d9047a573c3112f27c30d2d0bcb13d44de63946f8a8b3e947644d2debbd4

test:
  secret_key_base: 617e91cea5dfcf2f5ef7b36e8095fd31e0e72dbe966b2df497bc7bfb682be00e0ac99ae47b470e7e45b436b6643bbf55e501db8782018c09f274d242411a90ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
